#!/usr/bin/env bash

if [ "$1" == "" ]; then
    printf "\033[0;31m You should provide a name for migration. \033[0m\n";
    exit 1;
else
    dotnet ef migrations add $1 --project Backend/Blog.Data/Blog.Data.csproj --startup-project Blog.Api/Blog.Api.csproj --verbose
    exit 0;
fi
